"""initial

Revision ID: 270a181cbfaa
Revises: 
Create Date: 2026-03-28 17:49:27.866599
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = '270a181cbfaa'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organisationen',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('strasse', sa.String(length=255), nullable=True),
    sa.Column('plz', sa.String(length=10), nullable=True),
    sa.Column('ort', sa.String(length=255), nullable=True),
    sa.Column('telefon', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('logo_url', sa.Text(), nullable=True),
    sa.Column('branche', sa.String(length=100), nullable=True),
    sa.Column('plan', sa.String(length=50), nullable=False),
    sa.Column('trial_endet_am', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stripe_customer_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('checklisten_templates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organisation_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('norm', sa.String(length=100), nullable=True),
    sa.Column('beschreibung', sa.Text(), nullable=True),
    sa.Column('kategorie', sa.String(length=100), nullable=False),
    sa.Column('ist_system_template', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisationen.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_checklisten_templates_organisation_id'), 'checklisten_templates', ['organisation_id'], unique=False)
    op.create_table('standorte',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organisation_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('strasse', sa.String(length=255), nullable=True),
    sa.Column('plz', sa.String(length=10), nullable=True),
    sa.Column('ort', sa.String(length=255), nullable=True),
    sa.Column('beschreibung', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisationen.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_standorte_organisation_id'), 'standorte', ['organisation_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organisation_id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('vorname', sa.String(length=100), nullable=False),
    sa.Column('nachname', sa.String(length=100), nullable=False),
    sa.Column('rolle', sa.String(length=20), nullable=False),
    sa.Column('ist_aktiv', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisationen.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_organisation_id'), 'users', ['organisation_id'], unique=False)
    op.create_table('arbeitsmittel',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organisation_id', sa.String(length=36), nullable=False),
    sa.Column('standort_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('typ', sa.String(length=100), nullable=False),
    sa.Column('hersteller', sa.String(length=255), nullable=True),
    sa.Column('modell', sa.String(length=255), nullable=True),
    sa.Column('seriennummer', sa.String(length=255), nullable=True),
    sa.Column('baujahr', sa.Integer(), nullable=True),
    sa.Column('foto_url', sa.Text(), nullable=True),
    sa.Column('beschreibung', sa.Text(), nullable=True),
    sa.Column('norm', sa.String(length=100), nullable=True),
    sa.Column('pruef_intervall_monate', sa.Integer(), nullable=False),
    sa.Column('letzte_pruefung_am', sa.Date(), nullable=True),
    sa.Column('naechste_pruefung_am', sa.Date(), nullable=True),
    sa.Column('qr_code_url', sa.Text(), nullable=True),
    sa.Column('ampel_status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisationen.id'], ),
    sa.ForeignKeyConstraint(['standort_id'], ['standorte.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_arbeitsmittel_organisation_id'), 'arbeitsmittel', ['organisation_id'], unique=False)
    op.create_index(op.f('ix_arbeitsmittel_standort_id'), 'arbeitsmittel', ['standort_id'], unique=False)
    op.create_table('checklisten_punkte',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('template_id', sa.String(length=36), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('kategorie', sa.String(length=100), nullable=True),
    sa.Column('hinweis', sa.Text(), nullable=True),
    sa.Column('reihenfolge', sa.Integer(), nullable=False),
    sa.Column('ist_pflicht', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['checklisten_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_checklisten_punkte_template_id'), 'checklisten_punkte', ['template_id'], unique=False)
    op.create_table('pruefungen',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('arbeitsmittel_id', sa.String(length=36), nullable=False),
    sa.Column('checkliste_id', sa.String(length=36), nullable=False),
    sa.Column('pruefer_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('ergebnis', sa.String(length=20), nullable=True),
    sa.Column('bemerkung', sa.Text(), nullable=True),
    sa.Column('unterschrift_url', sa.Text(), nullable=True),
    sa.Column('unterschrift_name', sa.String(length=255), nullable=True),
    sa.Column('protokoll_pdf_url', sa.Text(), nullable=True),
    sa.Column('ist_abgeschlossen', sa.Boolean(), nullable=False),
    sa.Column('abgeschlossen_am', sa.DateTime(timezone=True), nullable=True),
    sa.Column('gestartet_am', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['arbeitsmittel_id'], ['arbeitsmittel.id'], ),
    sa.ForeignKeyConstraint(['checkliste_id'], ['checklisten_templates.id'], ),
    sa.ForeignKeyConstraint(['pruefer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pruefungen_arbeitsmittel_id'), 'pruefungen', ['arbeitsmittel_id'], unique=False)
    op.create_index(op.f('ix_pruefungen_pruefer_id'), 'pruefungen', ['pruefer_id'], unique=False)
    op.create_table('pruef_punkte',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('pruefung_id', sa.String(length=36), nullable=False),
    sa.Column('checklisten_punkt_id', sa.String(length=36), nullable=False),
    sa.Column('ergebnis', sa.String(length=20), nullable=False),
    sa.Column('bemerkung', sa.Text(), nullable=True),
    sa.Column('geprueft_am', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['checklisten_punkt_id'], ['checklisten_punkte.id'], ),
    sa.ForeignKeyConstraint(['pruefung_id'], ['pruefungen.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pruef_punkte_pruefung_id'), 'pruef_punkte', ['pruefung_id'], unique=False)
    op.create_table('maengel',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('pruefung_id', sa.String(length=36), nullable=False),
    sa.Column('pruef_punkt_id', sa.String(length=36), nullable=True),
    sa.Column('beschreibung', sa.Text(), nullable=False),
    sa.Column('schweregrad', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('frist', sa.Date(), nullable=True),
    sa.Column('erledigt_am', sa.DateTime(timezone=True), nullable=True),
    sa.Column('erledigt_kommentar', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['pruef_punkt_id'], ['pruef_punkte.id'], ),
    sa.ForeignKeyConstraint(['pruefung_id'], ['pruefungen.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_maengel_pruefung_id'), 'maengel', ['pruefung_id'], unique=False)
    op.create_table('fotos',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('mangel_id', sa.String(length=36), nullable=True),
    sa.Column('pruefung_id', sa.String(length=36), nullable=True),
    sa.Column('dateiname', sa.String(length=255), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('mime_type', sa.String(length=50), nullable=False),
    sa.Column('groesse_bytes', sa.Integer(), nullable=True),
    sa.Column('beschreibung', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['mangel_id'], ['maengel.id'], ),
    sa.ForeignKeyConstraint(['pruefung_id'], ['pruefungen.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fotos_mangel_id'), 'fotos', ['mangel_id'], unique=False)
    op.create_index(op.f('ix_fotos_pruefung_id'), 'fotos', ['pruefung_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fotos_pruefung_id'), table_name='fotos')
    op.drop_index(op.f('ix_fotos_mangel_id'), table_name='fotos')
    op.drop_table('fotos')
    op.drop_index(op.f('ix_maengel_pruefung_id'), table_name='maengel')
    op.drop_table('maengel')
    op.drop_index(op.f('ix_pruef_punkte_pruefung_id'), table_name='pruef_punkte')
    op.drop_table('pruef_punkte')
    op.drop_index(op.f('ix_pruefungen_pruefer_id'), table_name='pruefungen')
    op.drop_index(op.f('ix_pruefungen_arbeitsmittel_id'), table_name='pruefungen')
    op.drop_table('pruefungen')
    op.drop_index(op.f('ix_checklisten_punkte_template_id'), table_name='checklisten_punkte')
    op.drop_table('checklisten_punkte')
    op.drop_index(op.f('ix_arbeitsmittel_standort_id'), table_name='arbeitsmittel')
    op.drop_index(op.f('ix_arbeitsmittel_organisation_id'), table_name='arbeitsmittel')
    op.drop_table('arbeitsmittel')
    op.drop_index(op.f('ix_users_organisation_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_standorte_organisation_id'), table_name='standorte')
    op.drop_table('standorte')
    op.drop_index(op.f('ix_checklisten_templates_organisation_id'), table_name='checklisten_templates')
    op.drop_table('checklisten_templates')
    op.drop_table('organisationen')
    # ### end Alembic commands ###
